# Generated by Django 3.1.4 on 2020-12-14 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wiki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pageid', models.IntegerField()),
                ('wikitext', models.CharField(max_length=5000)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='halls.video')),
            ],
        ),
    ]
